# Generated by Django 3.2.8 on 2021-10-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundspreader', '0002_auto_20211030_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=800),
        ),
    ]
