# Generated by Django 3.2.8 on 2021-11-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundspreader', '0005_auto_20211101_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
    ]
