# Generated by Django 3.2.8 on 2021-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default='no bio', max_length=1600),
            preserve_default=False,
        ),
    ]
