# Generated by Django 3.2.8 on 2021-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greats', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='imgs',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
