# Generated by Django 3.2.8 on 2021-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greats', '0007_auto_20211029_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
